# Generated by Django 5.0.7 on 2025-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netcdflayer',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
