# Generated by Django 5.0.7 on 2024-09-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dataset_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastermaplayer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vectormaplayer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
