# Generated by Django 5.0.7 on 2024-09-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rastermaplayer_name_vectormaplayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
