# Generated by Django 5.0.7 on 2025-06-06 19:10

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_displayconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMVLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('default_style', models.JSONField(blank=True, null=True)),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Bounds/Extents of the Layer', null=True, srid=4326)),
                ('fmv_source_video', s3_file_field.fields.S3FileField(null=True)),
                ('fmv_video', s3_file_field.fields.S3FileField(null=True)),
                ('geojson_file', s3_file_field.fields.S3FileField(null=True)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FMVVectorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField()),
                ('map_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fmvlayer')),
            ],
        ),
    ]
