# Generated by Django 5.0.7 on 2025-06-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fmvlayer_fmvvectorfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmvlayer',
            name='fmv_fps',
            field=models.FloatField(blank=True, help_text='Frames per second of the FMV video.', null=True),
        ),
        migrations.AddField(
            model_name='fmvlayer',
            name='fmv_frame_count',
            field=models.IntegerField(blank=True, help_text='Total number of frames in the FMV video.', null=True),
        ),
        migrations.AddField(
            model_name='fmvlayer',
            name='fmv_video_duration',
            field=models.FloatField(blank=True, help_text='Duration of the FMV video in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='fmvlayer',
            name='fmv_video_height',
            field=models.IntegerField(blank=True, help_text='Height of the FMV video in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='fmvlayer',
            name='fmv_video_width',
            field=models.IntegerField(blank=True, help_text='Width of the FMV video in pixels.', null=True),
        ),
    ]
