# Generated by Django 5.0.7 on 2025-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dataset_options_dataset_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file_size',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
