# Generated by Django 5.0.7 on 2025-01-14 15:47

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fileitem_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('Complete', 'Complete'),
                            ('Running', 'Running'),
                            ('Error', 'Error'),
                            ('Queued', 'Queued'),
                        ],
                        help_text='Processing Status',
                        max_length=255,
                    ),
                ),
                (
                    'celery_id',
                    models.CharField(blank=True, help_text='Celery Task Id', max_length=255),
                ),
                ('output_metadata', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, help_text='Error text if an error occurs')),
                ('file_items', models.ManyToManyField(blank=True, to='core.fileitem')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
