# Generated by Django 5.0.7 on 2025-01-15 18:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_processingtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetCDFData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('default_style', models.JSONField(blank=True, null=True)),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                (
                    'dataset',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataset'
                    ),
                ),
                (
                    'file_item',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fileitem'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetCDFLayer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=255)),
                ('parameters', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color_scheme', models.CharField(blank=True, max_length=255)),
                (
                    'bounds',
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, help_text='Bounds/Extents of NetCDFLayer', null=True, srid=4326
                    ),
                ),
                (
                    'netcdf_data',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.netcdfdata'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetCDFImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('image', s3_file_field.fields.S3FileField()),
                ('slider_index', models.IntegerField()),
                (
                    'bounds',
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, help_text='Bounds/Extents of NetCDFLayer', null=True, srid=4326
                    ),
                ),
                (
                    'netcdf_layer',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.netcdflayer',
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
